version: "3.8"

services:
  ecommerce_app:
    tty: true
    build:
      context: .
      args:
        requirements: requirements/reqs.txt
    container_name: ecommerce_app
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ecommerce_db
    volumes:
      - .:/app:delegated
    ports:
      - 8001:8001
    depends_on:
      - postgres
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - ecommerce_network

  postgres:
    image: postgres:14
    container_name: ecommerce_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_db
    ports:
      - 5432:5432
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge
